# PRIMARY: #00d9ff
# SECONDARY: #0073ff
# TERTIARY: #cccccc
# HIGHLIGHT: #c100ff
# LINES: #4d4d4d
# WARNING: #ff5252
# POWERSHELL: #5b85e6
# BASH: #ab4923
# FISH: #00d9ff

format = """
${custom.topRowStarter}($username )[in](tertiary) $directory($git_branch( $git_state $git_commit)) \
([using](tertiary) [\\[](lines) \
($package )\
($c )\
($cmake )\
($cobol )\
($daml )\
($dart )\
($deno )\
($dotnet )\
($elixir )\
($elm )\
($erlang )\
($fennel )\
($gleam )\
($golang )\
($guix_shell )\
($haskell )\
($haxe )\
($helm )\
($java )\
($julia )\
($kotlin )\
($gradle )\
($lua )\
($nim )\
($nodejs )\
($ocaml )\
($opa )\
($perl )\
($php )\
($pulumi )\
($purescript )\
($python )\
($quarto )\
($raku )\
($rlang )\
($red )\
($ruby )\
($rust )\
($scala )\
($solidity )\
($swift )\
($terraform )\
($typst )\
($vlang )\
($vagrant )\
($zig )\
($buf )\
($nix_shell )\
($conda )\
($meson )\
($spack )\
($crystal )\
[\\]](lines) )\
($container )\
$all
${custom.bottomRowStarter}([\\(](lines)$shlvl[\\)](lines))$shell  $character\
($line_break)\
"""

right_format = "[Enter \"h\" for helpful commands](lines)"

palette = 'main'

[palettes.main]
primary = "#00d9ff"
secondary = "#0073ff"
tertiary = "#cccccc"
highlight = "#c100ff"
lines = "#4d4d4d"
warning = "#ff5252"
powershell = "#5b85e6"
bash = "#ab4923"
fish = "#00d9ff"


[container]
format = '[within](tertiary) [$symbol $name]($style)'

[cmd_duration]
format = '- took [$duration]($style) '
disabled = true

[custom.git_host_fish]
command = """\
if set remote_url (git ls-remote --get-url)
    set domain (string split ":" $remote_url)[1]
    set host (string split "@" $domain)[2]

    if string match -q "*github*" $host
        set GIT_REMOTE_SYMBOL "ï‚›"
    else if string match -q "*gitlab*" $host
        set GIT_REMOTE_SYMBOL "ïŠ–"
    else if string match -q "*bitbucket*" $host
        set GIT_REMOTE_SYMBOL "ï…±"
    else if string match -q "*git*" $host
        set GIT_REMOTE_SYMBOL "î™"
    end

    echo "$GIT_REMOTE_SYMBOL $host"
else
    echo "ï‡’ localhost"
end
"""
when = 'git rev-parse --is-inside-work-tree > /dev/null 2>&1'
shell = ["fish"]
style = 'bold yellow'
format = '[$output]($style)'
disabled = true

[custom.git_host_pwsh]
description = "Display symbol for remote Git server (pwsh)"
command = """
$remote_url = git ls-remote --get-url
$domain = ($remote_url -split ':')[0]
$remoteHost = ($domain -split '@')[1]

switch -regex ($remoteHost) {\
    'github'    { $symbol = 'ïˆ' }\
    'gitlab'    { $symbol = 'ïŠ–' }\
    'bitbucket' { $symbol = 'ï…±' }\
    Default    { $symbol = 'ï‡’'; $remoteHost = 'localhost' }\
}

echo "$symbol $remoteHost"
"""
when = "git rev-parse --is-inside-work-tree"
shell = ["pwsh", "-NoProfile", "-Command", "-"]
style = 'bold yellow'
format = '[$output]($style)'
disabled = true

[shlvl]
disabled = false
format = '[$shlvlî¾¯ ]($style)'
threshold = 3

[line_break]
disabled = true

[git_metrics]
disabled = true
format = '([\[](lines)( [+$added]($added_style))([ -$deleted]($deleted_style)) [\]](lines))'

[custom.topRowStarter]
style = "lines"
# format = "[â”Œ]($style)"
format = ""
when = true
disabled = false

# â”Œ
# â””

[custom.bottomRowStarter]
style = "lines"
# format = "[â””]($style)"
format = ""
when = true
disabled = false

[character]
success_symbol = '[ï„…](highlight)'
error_symbol = '[ï„…](highlight)'

[username]
format = "[$user]($style)"
show_always = false
style_root = "bold warning"
style_user = "bold primary"

# Second param
[hostname]
disabled = false
format = "[$hostname]($style)"
ssh_only = true
style = "primary"
trim_at = "-"
ssh_symbol = "î¬ "

[localip]
ssh_only = true
format = '[\($localipv4\)](secondary)'
disabled = false

# Third param
[directory]
style = "secondary"
repo_root_style = "secondary"
truncate_to_repo = true
read_only = " ó°Œ¾"
before_repo_root_style = "dimmed highlight"
format = '[$path]($style)[$read_only]($read_only_style)'

[sudo]
disabled = false
style = 'bold warning'
format = '[\(sudo\)]($style)'

[git_status]
ahead = "â‡¡[$count](tertiary)"
behind = "â‡£[$count](tertiary)"
deleted = " [$count](tertiary)[ó±€·](warning)"
conflicted = " [$count](tertiary)[ó°©Œ](#ffcc00)"
modified = " [$count](tertiary)[ó±‡¨](#ff9900)"
stashed = " [$count](tertiary)[î«­](highlight)"
untracked = " [$count](tertiary)[ó°»­](primary)"
staged = " [$count](tertiary)[ó±‰¦](#00ff88)"
renamed = " [$count](tertiary)[ó°•](#5fd7ff)"
diverged = " [ó±¦²](primary)[$ahead_count](tertiary)[ó±¦³](primary)[$behind_count](tertiary) "
format = '(([\[](lines)$ahead_behind[\]](lines))([\[](lines)$all_status [\]](lines)))'
disabled = true

[jobs]
format = '[$number JOB/S]($style)'
number_threshold = 1
symbol = ""

[shell]
fish_indicator = '[î¹](fish)'
powershell_indicator = '[ó°¨Š](powershell)'
bash_indicator = '[î¯Š](bash)'
unknown_indicator = '?'
disabled = false
format = "$indicator"

[os]
format = "[$symbol$name (\\(v$version\\))]($style)"
style = "bold blue"
disabled = true

[aws]
symbol = "îŒ½ "

[buf]
symbol = "ï’ "

[bun]
symbol = "îŠ"
format = '[$symbol( $version)]($style)'

[c]
symbol = "î˜"
format = '[$symbol( $version(-$name))]($style)'

[cmake]
symbol = "â–³"
format = '[$symbol( $version)]($style)'

[cobol]
symbol = "ï€“"
format = '[$symbol( $version)]($style)'

[conda]
symbol = "ï„Œ"
format = '\[[$symbol( $environment)]($style)\]'

[crystal]
symbol = "î˜¯"
format = '[$symbol( $environment)]($style)'

[daml]
format = '[$symbol( $version)]($style)'

[dart]
symbol = "î˜"
format = '[$symbol( $version)]($style)'

[deno]
format = '[$symbol( $version)]($style)'

[docker_context]
symbol = "ïŒˆ"
format = 'with [$symbol( $context)]($style)'

[dotnet]
symbol = "î¿"
format = '[$symbol( $version)(ğŸ¯ $tfm)]($style)'

[elixir]
symbol = "î˜­"
format = '[$symbol( $version\(OTP $otp_version\))]($style)'

[elm]
symbol = "î˜¬"
format = '[$symbol( $version)]($style)'

[erlang]
format = '[$symbol( $version)]($style)'

[fennel]
symbol = "îš¯"
format = '[$symbol( $version)]($style)'

[git_branch]
symbol = "ï˜ "
format = '[on](tertiary) [$symbol$branch(:$remote_branch)](highlight)'

[golang]
symbol = "î˜§"
format = '[$symbol( $version)]($style)'

[gradle]
symbol = "î™ "
format = '[$symbol( $version)]($style)'

[guix_shell]
symbol = "ïŒ¥"
format = '[$symbol]($style)'

[haskell]
symbol = "î·"
format = '[$symbol( $version)]($style)'

[haxe]
symbol = "î™¦"
format = '[$symbol( $version)]($style)'

[helm]
format = '[$symbol( $version)]($style)'

[java]
symbol = "î‰–"
format = '[$symbol( $version)](red)'

[julia]
symbol = "î˜¤"
format = '[$symbol( $version)]($style)'

[kotlin]
symbol = "î˜´"
format = '[$symbol( $version)]($style)'

[lua]
symbol = "î˜ "
format = '[$symbol( $version)]($style)'

[meson]
symbol = "ó°”·"
format = '[$symbol( $project)]($style)'

[nim]
symbol = "ó°†¥"
format = '[$symbol( $version)]($style)'

[nix_shell]
symbol = "ïŒ“"
format = '[$symbol$state( \($name\))]($style)'

[nodejs]
symbol = "î´"
format = '[$symbol( $version)]($style)'

[ocaml]
symbol = "î™º"
format = '[$symbol( $version)(\($switch_indicator$switch_name\))]($style)'

[opa]
format = '[$symbol( $version)]($style)'

[package]
symbol = "ó°—"
format = '[$symbol $version]($style)'

[perl]
symbol = "î™¾"
format = '[$symbol( $version)]($style)'

[php]
symbol = "î˜ˆ"
format = '[$symbol( $version)]($style)'

[pulumi]
format = '[$symbol($username@)$stack]($style)'

[purescript]
format = '[$symbol( $version)]($style)'

[python]
symbol = "î´› "
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)'

[raku]
format = '[$symbol( $version-$vm_version)]($style)'

[red]
format = '[$symbol( $version)]($style)'

[ruby]
symbol = "î‘"
format = '[$symbol( $version)]($style)'

[rust]
symbol = "ó±˜—"
format = '[$symbol( $version)]($style)'

[scala]
symbol = "îœ·"
format = '[$symbol( $version)]($style)'

[spack]
format = '[$symbol( $environment)]($style)'

[swift]
symbol = "î•"
format = '[$symbol( $version)]($style)'

[terraform]
format = '[$symbol$workspace]($style)'

[vagrant]
format = '[$symbol( $version)]($style)'

[vlang]
format = '[$symbol( $version)]($style)'

[zig]
symbol = "îš©"
format = '[$symbol( $version)]($style)'

[solidity]
format = '[$symbol( $version)]($style)'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "